### ISSUE TITLE
error: unable to pull docker images from ghcr

### ISSUE THREAD

**Issue by AbhijeetFasate13** [verifiable-presentation/impl#2]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What is the bug related to?

Docker Configuration

### Environment

```markdown
- OS:
- Node:
- Docker:
```

### Anything else?

<img width="1440" alt="Screenshot 2022-10-03 at 10 08 27 PM" src="https://user-images.githubusercontent.com/96332156/193631772-77c262ff-ab51-4c81-9a0c-573cef51b34f.png">

**Comment by AbhijeetFasate13** [comment]
Error response from daemon: Head "https://ghcr.io/v2/verifiable-presentation/registry/manifests/latest": unauthorized
I am getting this error, how to solve this?

**Comment by gamemaker1** [comment]
GitHub requires you to be logged in to GHCR using a PAT (Personal Access Token) to pull images. Could you please follow [this](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry#authenticating-to-the-container-registry) guide to login to GHCR, and then try pulling the image?
