### ISSUE TITLE
Error in command to retrieve the presentation

### ISSUE THREAD

**Issue by AbhijeetFasate13** [verifiable-presentation/impl#4]
There's an error in readme in command `http get :9277/presentations/{id}` to retrieve the presentation. Presentation should be retrieved from registry on port 9267 instead.

**Comment by gamemaker1** [comment]
Thanks for pointing this out, will fix it!

**Comment by gamemaker1** [comment]
Fixed in [e7b4150](https://github.com/verifiable-presentation/impl/commit/e7b415008fe1d3af38d792845ae00608cf411b98)
